//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Controls/GameOver.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @GameOver : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @GameOver()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""GameOver"",
    ""maps"": [
        {
            ""name"": ""Restart"",
            ""id"": ""99588ad5-7858-48e3-a1ab-cc98bb7df29d"",
            ""actions"": [
                {
                    ""name"": ""Restart"",
                    ""type"": ""Button"",
                    ""id"": ""09d4801d-2357-416d-b1ea-9aa68a4e581d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""7503d939-00a2-4b17-9a4a-86be9db2cea3"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Restart"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f3cf5ffd-be2d-4e80-a771-62d5c80d06b1"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Restart"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Restart
        m_Restart = asset.FindActionMap("Restart", throwIfNotFound: true);
        m_Restart_Restart = m_Restart.FindAction("Restart", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Restart
    private readonly InputActionMap m_Restart;
    private IRestartActions m_RestartActionsCallbackInterface;
    private readonly InputAction m_Restart_Restart;
    public struct RestartActions
    {
        private @GameOver m_Wrapper;
        public RestartActions(@GameOver wrapper) { m_Wrapper = wrapper; }
        public InputAction @Restart => m_Wrapper.m_Restart_Restart;
        public InputActionMap Get() { return m_Wrapper.m_Restart; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(RestartActions set) { return set.Get(); }
        public void SetCallbacks(IRestartActions instance)
        {
            if (m_Wrapper.m_RestartActionsCallbackInterface != null)
            {
                @Restart.started -= m_Wrapper.m_RestartActionsCallbackInterface.OnRestart;
                @Restart.performed -= m_Wrapper.m_RestartActionsCallbackInterface.OnRestart;
                @Restart.canceled -= m_Wrapper.m_RestartActionsCallbackInterface.OnRestart;
            }
            m_Wrapper.m_RestartActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Restart.started += instance.OnRestart;
                @Restart.performed += instance.OnRestart;
                @Restart.canceled += instance.OnRestart;
            }
        }
    }
    public RestartActions @Restart => new RestartActions(this);
    public interface IRestartActions
    {
        void OnRestart(InputAction.CallbackContext context);
    }
}
